# Generated by Django 5.0.6 on 2024-06-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='text',
        ),
        migrations.AddField(
            model_name='posts',
            name='description',
            field=models.TextField(default='Random Value for defaults sake.'),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_date',
            field=models.DateTimeField(default='2024-06-10'),
        ),
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.TextField(default='Random title value as a default'),
        ),
    ]
